### PR TITLE
Adding basic HTML, CSS and materialize widgets

### PR DESCRIPTION
**Pull request by himanshu-1608**
Added basic materialize widgets with JQueryUI widgets

### CODE REVIEW

**Comment by mostlypanda** [comment]
bhaiya hum bhi contribute krenge is project me

**Comment by himanshu-1608** [comment]
> bhaiya hum bhi contribute krenge is project me

Are bhai ye alag h scene thoda..btate hai whatsapp pe ruko 😆

**Review by insaiyann — APPROVED** [review]
OurCode

**Review by Kanishkgoel55497 — APPROVED** [review]
OurCode

**Pull request merged**
